#
#
# Try to find the SFEMOVIE libraries
# Once done this will define
#
# SFEMOVIE_FOUND			- system has SFEMOVIE
# SFEMOVIE_INCLUDE_DIR		- path to Movie.h
# SFEMOVIE_LIBRARY			- the library that must be included
#
#

IF (SFEMOVIE_LIBRARY AND SFEMOVIE_INCLUDE_DIR)
  SET(SFEMOVIE_FOUND "YES")
ELSE (SFEMOVIE_LIBRARY AND SFEMOVIE_INCLUDE_DIR)
  FIND_PATH(SFEMOVIE_INCLUDE_DIR Movie.hpp PATHS /usr/local/include/sfeMovie /usr/include/sfeMovie)
  FIND_LIBRARY(SFEMOVIE_LIBRARY sfeMovie PATHS /usr/local/lib /usr/lib)
  
  IF (SFEMOVIE_INCLUDE_DIR AND SFEMOVIE_LIBRARY)
    SET(SFEMOVIE_FOUND "YES")
  ELSE (SFEMOVIE_INCLUDE_DIR AND SFEMOVIE_LIBRARY)
    SET(SFEMOVIE_FOUND "NO")
  ENDIF (SFEMOVIE_INCLUDE_DIR AND SFEMOVIE_LIBRARY)
ENDIF (SFEMOVIE_LIBRARY AND SFEMOVIE_INCLUDE_DIR)

IF (SFEMOVIE_FOUND)
  MESSAGE(STATUS "Found SFEMOVIE libraries at ${SFEMOVIE_LIBRARY} and includes at ${SFEMOVIE_INCLUDE_DIR}")
ELSE (SFEMOVIE_FOUND)
  IF (SFEMOVIE_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SFEMOVIE libraries")
  ENDIF (SFEMOVIE_FIND_REQUIRED)
ENDIF (SFEMOVIE_FOUND)
